modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "crawl"
version = "${version}"
displayName = "${mod_name}"
logoFile = "assets/crawl/icon.png"
logoBlur = false
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.crawl]]
modId = "forge"
mandatory = true
type = "required"
versionRange = "[${forge_minimum_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crawl]]
modId = "minecraft"
mandatory = true
type = "required"
versionRange = "${forge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
