plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
}

base {
	archivesName = mod_id
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

compileJava.source project(":common").sourceSets.main.allSource

loom {
	accessWidenerPath = file("src/main/resources/crawl.accesswidener")
	mixin {
		useLegacyMixinAp = false
	}
	runs {
		client {
			client()
			configName = 'Fabric Client'
			ideConfigGenerated = true
			runDir = '../run'
			// programArg "--username=_fewizz"
			appendProjectPathToConfigName = false
		}
		server {
			server()
			configName = 'Fabric Server'
			ideConfigGenerated = true
			runDir = '../run'
			appendProjectPathToConfigName = false
		}
	}
}

processResources {
	from project(":common").sourceSets.main.resources

	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
