plugins {
	id "net.fabricmc.fabric-loom" version "${fabric_loom_version}"
}

base {
	archivesName = "crawl-mc${minecraft_version}-fabric"
}

repositories {
	maven {
		name = "Terraformers"
		url = "https://maven.terraformersmc.com/"
	}
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = uri("https://api.modrinth.com/maven")
			}
		}
		filter {
			includeGroup("maven.modrinth")
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
	compileOnly "maven.modrinth:not-enough-animations:${project.not_enough_animations_modrinth_fabric_id}"
	compileOnly "maven.modrinth:first-person-model:${project.first_person_model_fabric_id}"
}

compileJava.source project(":common").sourceSets.main.allSource

loom {
	accessWidenerPath = file("src/main/resources/crawl.accesswidener")
	mixin {
		useLegacyMixinAp = false
	}
	runs {
		client {
			client()
			configName = 'Fabric Client'
			ideConfigGenerated = true
			runDir = '../run'
			// programArg "--username=_fewizz"
			appendProjectPathToConfigName = false
		}
		server {
			server()
			configName = 'Fabric Server'
			ideConfigGenerated = true
			runDir = '../run'
			appendProjectPathToConfigName = false
		}
	}
}

processResources {
	from project(":common").sourceSets.main.resources

	var expandProps = [
		'version'                       : version,
		'minecraft_version'             : minecraft_version,
		'mod_name'                      : mod_name,
		'mod_author'                    : mod_author,
		'description'                   : project.description,
		'java_version'                  : java_version,
		'fabric_minecraft_version_range': project.fabric_minecraft_version_range
	]

	filesMatching("fabric.mod.json") {
		expand expandProps
	}

	inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
