version=0.15.0
group=fewizz.canpipe
java_version=25

minecraft_version=26.2
mod_name=Crawl
mod_author=fewizz
license=WTFPL
credits=
description=Allows you to crawl

# https://modrinth.com/mod/modmenu/versions
modmenu_version=20.0.0-beta.3

# Fabric
# https://maven.fabricmc.net/net/fabricmc/fabric-loom/
fabric_loom_version=1.17.9
# https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/
fabric_version=0.149.2+26.2
# https://maven.fabricmc.net/net/fabricmc/fabric-loader/
fabric_loader_version=0.19.3
fabric_minecraft_version_range=~26.2
# https://modrinth.com/mod/not-enough-animations/versions?l=fabric
not_enough_animations_modrinth_fabric_id=67xQnLDS
# https://modrinth.com/mod/first-person-model/versions?l=fabric
first_person_model_fabric_id=l2EOp6Y3

# NeoForge
# https://projects.neoforged.net/neoforged/moddevgradle
mod_dev_gradle_version=2.0.141
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
# https://projects.neoforged.net/neoforged/neoforge
neoforge_current_version=26.2.0.6-beta
neoforge_minimum_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)
neoforge_minecraft_version_range=[26.2, 26.3)
# https://modrinth.com/mod/not-enough-animations/versions?l=neoforge
not_enough_animations_modrinth_neoforge_id=KzaQdqHS
# https://modrinth.com/mod/first-person-model/versions?l=neoforge
first_person_model_neoforge_id=TH7Cx1s8

# Forge
# https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle/index.html
forge_gradle_version=6.0.54
forge_loader_version_range=[56,)
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_current_version=65.0.5
forge_minimum_version=65.0.0
forge_minecraft_version_range=[26.2, 26.3)
# https://modrinth.com/mod/not-enough-animations/versions?l=forge
not_enough_animations_modrinth_forge_id=MPCX6s5C
# https://modrinth.com/mod/first-person-model/versions?l=forge
first_person_model_forge_id=2BVgMyjz

# Gradle
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
