version=0.14.5
group=fewizz.canpipe
java_version=21

minecraft_version=1.21.5
mod_name=Crawl
mod_author=fewizz
license=WTFPL
credits=
description=Allows you to crawl

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830

modmenu_version=14.0.0-rc.2

not_enough_animations_modrinth_fabric_id=prj4BdjU
not_enough_animations_modrinth_neoforge_id=8FfTQxID

first_person_model_fabric_id=jGNLTOaM
first_person_model_neoforge_id=mWDTHrkc

# Fabric
fabric_version=0.120.0+1.21.5
fabric_loader_version=0.16.14
fabric_minecraft_version_range=>=1.21.4 <=1.21.5

# NeoForge
neoforge_current_version=21.5.41-beta
neoforge_minimum_version=21.4.54-beta
neoforge_loader_version_range=[4,)
neoforge_minecraft_version_range=[1.21.4, 1.21.5]

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
