plugins {
	id "fabric-loom" version "${fabric_loom_version}"
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = uri("https://api.modrinth.com/maven")
			}
		}
		filter {
			includeGroup("maven.modrinth")
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	modCompileOnly "maven.modrinth:not-enough-animations:${project.not_enough_animations_modrinth_fabric_id}"
	modCompileOnly "maven.modrinth:first-person-model:${project.first_person_model_fabric_id}"
}

loom {
	accessWidenerPath = new File(rootDir, "fabric/src/main/resources/crawl.accesswidener")
	runs {}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
