modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]] #mandatory
modId = "crawl"
version = "${version}"
displayName = "${mod_name}"
logoFile = "assets/crawl/icon.png"
logoBlur = false
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "crawl.mixins.json"

[[mixins]]
config = "crawl.client.mixins.json"

[[mixins]]
config = "crawl.compat.nea.mixins.json"

[[mixins]]
config = "crawl.compat.fpm.mixins.json"

[[dependencies.crawl]] #optional
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_minimum_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crawl]]
modId = "minecraft"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
