plugins {
	id "net.neoforged.moddev" version "${mod_dev_gradle_version}"
}

repositories {
	exclusiveContent {
		forRepository {
			maven {
				name = "Modrinth"
				url = uri("https://api.modrinth.com/maven")
			}
		}
		filter {
			includeGroup("maven.modrinth")
		}
	}
}

dependencies {
	compileOnly project(":common")
	implementation "maven.modrinth:not-enough-animations:${project.not_enough_animations_modrinth_neoforge_id}"
	implementation "maven.modrinth:first-person-model:${project.first_person_model_neoforge_id}"
}

base {
	archivesName = "crawl"
}

neoForge {
	version = neoforge_current_version
	accessTransformers.from(file("src/main/resources/META-INF/accesstransformer.cfg"))

	runs {
		client {
			client()
			ideName = "NeoForge Client"
			// programArguments.addAll("--username", "Player3")
			gameDirectory = new File(project.rootDir, "/run")
		}
		server {
			server()
			ideName = "NeoForge Server"
			programArgument "--nogui"
			gameDirectory = new File(project.rootDir, "/run")
		}
	}

	mods {
		"crawl" {
			sourceSet sourceSets.main
		}
	}
}

compileJava.source project(":common").sourceSets.main.allSource

processResources {
	from project(":common").sourceSets.main.resources

	var expandProps = [
		"version"                         : version,
		"minecraft_version"               : minecraft_version,
		"mod_name"                        : mod_name,
		"mod_author"                      : mod_author,
		"license"                         : license,
		"description"                     : project.description,
		"neoforge_minimum_version"        : neoforge_minimum_version,
		"neoforge_loader_version_range"   : neoforge_loader_version_range,
		"neoforge_minecraft_version_range": neoforge_minecraft_version_range,
		"credits"                         : credits,
	]

	filesMatching(["META-INF/neoforge.mods.toml"]) {
		expand expandProps
	}

	inputs.properties(expandProps)
}
